global:
    scrape_interval: 15s # Default scrape interval

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    # Revvly Go Application
    - job_name: 'revvly'
      static_configs:
        - targets: ['revvly.railway.internal:8080']
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s

    # - job_name: 'example_api'
    #   scheme: http
    #   static_configs:
    #     - targets: ['example_api:9091']
